import type { Reader } from "./reader";

export interface Book {
  isbn: string;
  category: Category;
  bookName: string;
  author: string;
  publisher: string;
  publishDate: number;
  unitPrice: number;
  imgUrl: string;
  summary: string;
  allNum: number;
  tags: string;
  lastNum: number;
  status: number;
}

export interface Category {
  id: number;
  categoryName: string;
}

// Generated by https://quicktype.io

export interface BorrowBook {
  id:         number;
  book:       Book;
  reader:     Reader;
  borrowDate: number;
  returnDate: number;
  fine:       number;
  status:     number;
}

export interface Category {
  id:           number;
  categoryName: string;
}
